Repository FehStella/devops-aula07, pull requests merged in 2018-10, with the labels that each got.

#16 Integrar requisitos v1.1
  docs/requisitos
Labels: análise

#18 V1.1 programacao
  src/jogovelha.py
Labels: programação

#20 Integrar Testes v1.1
  src/testes_inic.py
  src/testes_jogar.py
Labels: testes

#21 Gerar release v1.1
  src/jogovelha.py
  src/testes_inic.py
  src/testes_jogar.py
Labels: operações
